platform :ios,'7.0'

pod 'AFNetworking', '~> 2.5.3'
pod 'HexColors', '~> 2.2.1'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'SDWebImage', '~> 3.7.2'
pod 'AHKNavigationController', '~> 1.2'
pod 'FMDB', '~> 2.5'
pod 'SwipeView', '~> 1.3.2'
pod 'MJRefresh', '~> 2.4.12'
pod 'CocoaAsyncSocket', '~> 7.4.1'
pod 'BlocksKit', '~> 2.2.5'
pod 'Masonry', '~> 0.6.3’
pod 'SSKeychain', '~> 1.2.3'
pod 'TPKeyboardAvoiding', '~> 1.2.10'
pod 'Facebook-iOS-SDK', '~> 4.1.0'
pod 'WeiboSDK', '~> 3.1.3'
pod 'MXSegmentedPager', '~> 1.2.1'
pod 'pop', '~> 1.0.6'
pod 'Fingertips'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'RegexKitLite', '~> 4.0'
pod 'YYText', '~> 0.9.13'
pod 'OpenUDID', '~> 1.0.0'
pod 'DZNEmptyDataSet'
pod 'MJExtension', '~> 3.0.4'
